"""empty message

Revision ID: 1a4e57940d37
Revises: fb2873e8e897
Create Date: 2019-03-29 02:36:34.206664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4e57940d37'
down_revision = 'fb2873e8e897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_request', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('feature_request', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_feature_request_created_at'), 'feature_request', ['created_at'], unique=False)
    op.create_index(op.f('ix_feature_request_updated_at'), 'feature_request', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_request_updated_at'), table_name='feature_request')
    op.drop_index(op.f('ix_feature_request_created_at'), table_name='feature_request')
    op.drop_column('feature_request', 'updated_at')
    op.drop_column('feature_request', 'created_at')
    # ### end Alembic commands ###
